package org.sunhp.rcampus.bean;

public class Chapter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.chapter_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long chapterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.chapter_name
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String chapterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.chapter_descrbe
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String chapterDescrbe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_chapter.chapter_order
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Integer chapterOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.chapter_id
     *
     * @return the value of tb_chapter.chapter_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.chapter_id
     *
     * @param chapterId the value for tb_chapter.chapter_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.chapter_name
     *
     * @return the value of tb_chapter.chapter_name
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getChapterName() {
        return chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.chapter_name
     *
     * @param chapterName the value for tb_chapter.chapter_name
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setChapterName(String chapterName) {
        this.chapterName = chapterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.chapter_descrbe
     *
     * @return the value of tb_chapter.chapter_descrbe
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getChapterDescrbe() {
        return chapterDescrbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.chapter_descrbe
     *
     * @param chapterDescrbe the value for tb_chapter.chapter_descrbe
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setChapterDescrbe(String chapterDescrbe) {
        this.chapterDescrbe = chapterDescrbe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_chapter.chapter_order
     *
     * @return the value of tb_chapter.chapter_order
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Integer getChapterOrder() {
        return chapterOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_chapter.chapter_order
     *
     * @param chapterOrder the value for tb_chapter.chapter_order
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setChapterOrder(Integer chapterOrder) {
        this.chapterOrder = chapterOrder;
    }
}