package org.sunhp.rcampus.bean;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_name
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_note
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String courseNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.exam_intro
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String examIntro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.exam_page
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String examPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.exam_solution
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String examSolution;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.exam_note
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String examNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.course_order
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Integer courseOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_course.chapter
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long chapter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_id
     *
     * @return the value of tb_course.course_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_id
     *
     * @param courseId the value for tb_course.course_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_name
     *
     * @return the value of tb_course.course_name
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_name
     *
     * @param courseName the value for tb_course.course_name
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_note
     *
     * @return the value of tb_course.course_note
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getCourseNote() {
        return courseNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_note
     *
     * @param courseNote the value for tb_course.course_note
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setCourseNote(String courseNote) {
        this.courseNote = courseNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.exam_intro
     *
     * @return the value of tb_course.exam_intro
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getExamIntro() {
        return examIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.exam_intro
     *
     * @param examIntro the value for tb_course.exam_intro
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setExamIntro(String examIntro) {
        this.examIntro = examIntro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.exam_page
     *
     * @return the value of tb_course.exam_page
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getExamPage() {
        return examPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.exam_page
     *
     * @param examPage the value for tb_course.exam_page
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setExamPage(String examPage) {
        this.examPage = examPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.exam_solution
     *
     * @return the value of tb_course.exam_solution
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getExamSolution() {
        return examSolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.exam_solution
     *
     * @param examSolution the value for tb_course.exam_solution
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setExamSolution(String examSolution) {
        this.examSolution = examSolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.exam_note
     *
     * @return the value of tb_course.exam_note
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getExamNote() {
        return examNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.exam_note
     *
     * @param examNote the value for tb_course.exam_note
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setExamNote(String examNote) {
        this.examNote = examNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.course_order
     *
     * @return the value of tb_course.course_order
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Integer getCourseOrder() {
        return courseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.course_order
     *
     * @param courseOrder the value for tb_course.course_order
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setCourseOrder(Integer courseOrder) {
        this.courseOrder = courseOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_course.chapter
     *
     * @return the value of tb_course.chapter
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getChapter() {
        return chapter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_course.chapter
     *
     * @param chapter the value for tb_course.chapter
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setChapter(Long chapter) {
        this.chapter = chapter;
    }
}