package org.sunhp.rcampus.bean;

public class Judge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_judge.judge_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long judgeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_judge.exam_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long examId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_judge.judge_item
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String judgeItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_judge.judge_type
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String judgeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_judge.judge_tips
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private String judgeTips;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_judge.judge_id
     *
     * @return the value of tb_judge.judge_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getJudgeId() {
        return judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_judge.judge_id
     *
     * @param judgeId the value for tb_judge.judge_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setJudgeId(Long judgeId) {
        this.judgeId = judgeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_judge.exam_id
     *
     * @return the value of tb_judge.exam_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getExamId() {
        return examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_judge.exam_id
     *
     * @param examId the value for tb_judge.exam_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setExamId(Long examId) {
        this.examId = examId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_judge.judge_item
     *
     * @return the value of tb_judge.judge_item
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getJudgeItem() {
        return judgeItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_judge.judge_item
     *
     * @param judgeItem the value for tb_judge.judge_item
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setJudgeItem(String judgeItem) {
        this.judgeItem = judgeItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_judge.judge_type
     *
     * @return the value of tb_judge.judge_type
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getJudgeType() {
        return judgeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_judge.judge_type
     *
     * @param judgeType the value for tb_judge.judge_type
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setJudgeType(String judgeType) {
        this.judgeType = judgeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_judge.judge_tips
     *
     * @return the value of tb_judge.judge_tips
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public String getJudgeTips() {
        return judgeTips;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_judge.judge_tips
     *
     * @param judgeTips the value for tb_judge.judge_tips
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setJudgeTips(String judgeTips) {
        this.judgeTips = judgeTips;
    }
}