package org.sunhp.rcampus.bean;

public class Judge {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_judge.judge_id
	 * 
	 * @mbggenerated Fri Apr 28 16:03:04 CST 2017
	 */
	private Long judgeId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_judge.exam_id
	 * 
	 * @mbggenerated Fri Apr 28 16:03:04 CST 2017
	 */
	private Long courseId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_judge.judge_item
	 * 
	 * @mbggenerated Fri Apr 28 16:03:04 CST 2017
	 */
	private String judgeAnswer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_judge.judge_type
	 * 
	 * @mbggenerated Fri Apr 28 16:03:04 CST 2017
	 */
	private String judgeProblem;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column tb_judge.judge_tips
	 * 
	 * @mbggenerated Fri Apr 28 16:03:04 CST 2017
	 */
	private String judgeTips;

	public Long getJudgeId() {
		return judgeId;
	}

	public void setJudgeId(Long judgeId) {
		this.judgeId = judgeId;
	}

	public Long getCourseId() {
		return courseId;
	}

	public void setCourseId(Long courseId) {
		this.courseId = courseId;
	}

	public String getJudgeAnswer() {
		return judgeAnswer;
	}

	public void setJudgeAnswer(String judgeAnswer) {
		this.judgeAnswer = judgeAnswer;
	}

	public String getJudgeProblem() {
		return judgeProblem;
	}

	public void setJudgeProblem(String judgeProblem) {
		this.judgeProblem = judgeProblem;
	}

	public String getJudgeTips() {
		return judgeTips;
	}

	public void setJudgeTips(String judgeTips) {
		this.judgeTips = judgeTips;
	}

}