package org.sunhp.rcampus.bean;

import java.util.Date;

public class Progress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_progress.progress_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long progressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_progress.course_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long courseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_progress.user_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_progress.point
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Double point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_progress.create_time
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_progress.update_time
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_progress.progress_id
     *
     * @return the value of tb_progress.progress_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getProgressId() {
        return progressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_progress.progress_id
     *
     * @param progressId the value for tb_progress.progress_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setProgressId(Long progressId) {
        this.progressId = progressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_progress.course_id
     *
     * @return the value of tb_progress.course_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_progress.course_id
     *
     * @param courseId the value for tb_progress.course_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setCourseId(Long courseId) {
        this.courseId = courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_progress.user_id
     *
     * @return the value of tb_progress.user_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_progress.user_id
     *
     * @param userId the value for tb_progress.user_id
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_progress.point
     *
     * @return the value of tb_progress.point
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Double getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_progress.point
     *
     * @param point the value for tb_progress.point
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setPoint(Double point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_progress.create_time
     *
     * @return the value of tb_progress.create_time
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_progress.create_time
     *
     * @param createTime the value for tb_progress.create_time
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_progress.update_time
     *
     * @return the value of tb_progress.update_time
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_progress.update_time
     *
     * @param updateTime the value for tb_progress.update_time
     *
     * @mbggenerated Fri Apr 28 16:03:04 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}