package org.sunhp.rcampus.bean;

import java.util.Date;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.store_id
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private Long storeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.store_name
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private String storeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.address
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.type
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.tel
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.start_date
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.license
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private String license;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.manager_name
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private String managerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_store.manager_id
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    private Long managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.store_id
     *
     * @return the value of tb_store.store_id
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public Long getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.store_id
     *
     * @param storeId the value for tb_store.store_id
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setStoreId(Long storeId) {
        this.storeId = storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.store_name
     *
     * @return the value of tb_store.store_name
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.store_name
     *
     * @param storeName the value for tb_store.store_name
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.address
     *
     * @return the value of tb_store.address
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.address
     *
     * @param address the value for tb_store.address
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.type
     *
     * @return the value of tb_store.type
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.type
     *
     * @param type the value for tb_store.type
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.tel
     *
     * @return the value of tb_store.tel
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.tel
     *
     * @param tel the value for tb_store.tel
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.start_date
     *
     * @return the value of tb_store.start_date
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.start_date
     *
     * @param startDate the value for tb_store.start_date
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.license
     *
     * @return the value of tb_store.license
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public String getLicense() {
        return license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.license
     *
     * @param license the value for tb_store.license
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setLicense(String license) {
        this.license = license;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.manager_name
     *
     * @return the value of tb_store.manager_name
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.manager_name
     *
     * @param managerName the value for tb_store.manager_name
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_store.manager_id
     *
     * @return the value of tb_store.manager_id
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_store.manager_id
     *
     * @param managerId the value for tb_store.manager_id
     *
     * @mbggenerated Mon Oct 24 23:56:44 CST 2016
     */
    public void setManagerId(Long managerId) {
        this.managerId = managerId;
    }
}